{% set version = "2017.10.17.21.7" %}
{% set pkgname = "hiveplot" %}

package:
    name: {{ pkgname }}
    version: {{ version }}

source:
    fn: {{ pkgname }}-{{ version }}.tar.gz
    url: https://pypi.io/packages/source/{{ pkgname[0] }}/{{ pkgname }}/{{ pkgname }}-{{ version }}.tar.gz
    md5: b3e74345f0b9da09fb5a275d43f2dd95

build:
    number: 0
    script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
    build:
        - python
        - setuptools
        - pip
    run:
        - python
        - matplotlib
        - numpy

test:
    imports:
        - hiveplot

about:
    home: http://github.com/ericmjl/hiveplot
    license: MIT
    summary: 'Hive plots in Python!'

extra:
    recipe-maintainers:
        - ericmjl
