travis:
  secure:
    BINSTAR_TOKEN: SP7mtFb5PTRaArHlypHBPi/11EWfOPbU7CWWPc87uPuBcyVxLVcrFeT54CoBM3rNRlVsdS1jVAi0o+r5dDX85CSh2cQjVpsjk6S9KeWupoKeegG0/+/H1GGDsINXh6C9wxSRl8tPZICAfrdS4eCzo6N/p6EOHpZp/on6llv/Z8MikytEp8s6rEl/wFuVqLQG/I/2DoLHc8GdroYesG/Eut9A9findT6ERisVp6Tw8OBg2v9+PdfPAA2cX7wcL2ETttHGfcMfdyc5Qar6RAf3QzMT3+acQ01yOcRxhyEr1534zw+Rkw5Ajoh5s6B57rWd7Tsrh56SBwK570taOHWbmcgP+3ToJTqSpfbDpGDxnrolgNwhRT96sU9dCfgydQqrsu0UQ4GwzmcgRaXZXIJcQxz3RTSEzT8Um2FfJQ5bnARlSG4yyXHVwX+de859ONWlNSG7QNWgCP/oE/o1Ssa7VZ7qkKy8vl+QZL3+199vio3hUoffADQRt31HFDLxa0ylbTTqYtUi6Ygm1XWyvfkDylgZr8AJlSKBUdVOVXyl6D7uWMVrLbYk0pwwqOG8wF9gWzVXTg8ttyLsJNUzo95B8URkCZCBitD/MKueXjGDICwOf+SkxOPpfl9wtJffhw5VKSsJ2J/ypVQE0kJ5ZcMRn1ejcG+4HG19rPZLuwBFvQs=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
