travis:
  secure:
    BINSTAR_TOKEN: mlpMZ9mo9hzlZo9kh5HPsbSmteSo4TGzYNedWV8EqpWVZuBBmYuxxE8WgNA8NkKCKnH9OfEM9/Sr4QX9Bi9T9TJyUJJhZCilSUsy2SFayHg2WNOTjc3KoqxUB0emC3fHlW69ysjXDmU7XB1PVP5EAGaWiF8QPn3LH7bhkVLFz6zaqXbW9snPs/RGP27SK/lzOPJcsfGv2jPdWv7UZom5ll9zk+1gZPO1KTNCFh5UnJmu/92kB3SlgmKfAqQn3seprF3xiCSPspj7qJz7eVizOPIlwUIE8Ikf3XgYpl3sJzBWHIliqMT4lqK+uBtajtVJM3tFn6wx8zBcAQzC3KgoTcxMS3+v24IhR7ByuGSLYEyJmPpgZAlIpGqV6yaMLE/YEGAHwPYo0Q8rjQs+RhJIyiBqkJgofZXoClNDAQa99olwNOMBiGtVdwhtC1LEpcP3Gt+1LrVr75yjz2bRD3UrxJ2/hBl0OIJr3QDM9srlNMGeXRYjHvDs0CV3XLX+cV9HC5zgg6BeyH5iYj2b3674bi28MEpnQu5/0AQaD3nnZqWfwipvkHgjyeNc38RboSuscq5gT4iEuYmNx3rMHG3W+WXR1JBa3biqpuOmfDQ3AjohEOGov/GZtl/zJqCPYWx8iusOUdypHSqeM2Yg6TEXI2tiCtp3wibUzC3A0Zvskls=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
